//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> edge_length { get; set; }
        public Nullable<decimal> edge_width { get; set; }
        public Nullable<decimal> min_distance_item { get; set; }
        public Nullable<decimal> radius { get; set; }
        public Nullable<int> items_sum { get; set; }
        public Nullable<System.TimeSpan> elapsed_time { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> ts_user_id { get; set; }
    }
}
